### ISSUE TITLE
Cannot retrieve password

### ISSUE THREAD

**Issue by svetoslavnikolov** [midasplatform/Midas#160]
I created an account and logged in. 
Second time I tried to log in, I got a message that either the password or the E-mail were not valid.

I am certain that the password is correct. 

The web page is missing "Forgotten password" functionality. 
The website is:
http://qidw.rsna.org/

I had to register 3 times. I am using different E-mails, but same password.

**Comment by jamiesnape** [comment]
Please contact the administrator of that site.

**Comment by svetoslavnikolov** [comment]
Thanks for the answer.

I sincerely apologize to have wasted your time.

Svetoslav
