### ISSUE TITLE
Fail to upgrade PrivateModules with Midas 3.4.2

### ISSUE THREAD

**Issue by felixveysseyre** [midasplatform/Midas#258]
Hello,

I was trying to install several PrivateModules inside an instance of Midas 3.4.2.

After adding them correctly to Midas through the Admin section, I tried to upgrade them to latest version. The admin section was telling me they were already updated which was false.

Looking at https://github.com/midasplatform/Midas/blob/3.4.2/core/controllers/components/UtilityComponent.php#L450, it seems that ini files are searched only in _modules_ directory and not _privateModules_ directory.

Hope it will help.

**Comment by cpatrick** [comment]
That is correct. behavior. We removed the `privateModules` code paths as they added to request latency and (more importantly) code complexity. The modules should function correctly from the `modules` directory.

**Comment by felixveysseyre** [comment]
Weird thing therefore, I was able to add modules from a privateModules directory I created my self

**Comment by cpatrick** [comment]
That is odd...
