### ISSUE TITLE
I can not modify users information to add them to administrator a collection

### ISSUE THREAD

**Issue by hjmjohnson** [midasplatform/Midas#265]
```
The system has encountered the following error:
Object of class UserDao could not be converted to string
In /projects/src/Midas3/core/models/pdo/UserModel.php, line: 116
At 18:08:26 2017-03-02


Please notify your administrator with this information.
```

**Comment by mgrauer** [comment]
Thanks for the report. We have seen this in some Midas instances but have not had the resources to investigate.  

Can you explain what you are trying to do in more detail?  Is this blocking you, or are you simply being a good citizen by trying to report it (for which, again, thanks) ?

**Comment by hjmjohnson** [comment]
This is definitely blocking us.  We want to upload data to MIDAS as part of the test suite needed for deploying applications to the Slicer infrastructure.

 

Without new test data sets, we can not perform the tests.

 

Hans

 

 

--

**Comment by jcfr** [comment]
Hi @hjmjohnson , 

To be address the problem, could you confirm that this is happening with the `BRAINSTools` community served of http://slicer.kitware.com/midas3/ 

Thanks
Jc

**Comment by hjmjohnson** [comment]
Yes!

 

Hans

 

--

**Comment by jcfr** [comment]
This has been fixed on https://slicer.kitware.com and https://midas3.kitware.com

Thanks for your patience, 
Jc

**Comment by jcfr** [comment]
Cc: @pieper
