### ISSUE TITLE
Deprecate / remove java applet for large download ?

### ISSUE THREAD

**Issue by jcfr** [midasplatform/Midas#82]
While trying to download 1.8GB from http://aladdin.kitware.com (Midas 3.2.11), after clicking on the download link for a folder, I am proposed two options. See screenshot below.

![midas-3-large-download-requested](https://cloud.githubusercontent.com/assets/219043/5415131/d6e03888-81f2-11e4-9929-89aaa5ca6f3c.png)

As suggested, I have clicked on the "Yes, use large downloader". Then, on windows:
1. firefox asked me to manually install Java because of [security reasons](https://support.mozilla.org/en-US/kb/use-java-plugin-to-view-interactive-content)
2. after following the instruction, I managed to install java
3. going back to the page, the applet failed complaining the current security settings can't accept self signed certificate
4. I then added a security exception (Start menu -> Programs -> Java -> Configure Java -> Security) by listing http://aladdin.kitware.com as an exception
5. going back to the page, I was able to see the applet ... clicking on Download failed with a timeout

Finally, I gave a try with the normal downloader .. and already 0.5 GB have been downloaded

Moving forward, I suggest we disable the java downloader. It should be enabled explicitly on instance that require it.

**Comment by jamiesnape** [comment]
It is all in a separate module now, so you can easily disable it, or we could just delete it without impacting the core.

I am going to try to get the last handful of commits in by the middle of next week, so the version 3.4 codebase should be finalized around January 15.

**Comment by jcfr** [comment]
+1

--

**Comment by jamiesnape** [comment]
I will sign the jar before release, so at least there will be slightly fewer warnings.

**Comment by jamiesnape** [comment]
Rolling this ticket into #71 regarding the signing of jars.
