### ISSUE TITLE
Write installation and upgrade documentation

### ISSUE THREAD

**Issue by jamiesnape** [midasplatform/Midas#88]

**Comment by mgrauer** [comment]
On Ubuntu 14.04 I needed to make MIDAS_PATH/core/configs writeable by www-data to proceed through the installation.  Otherwise I was stuck on the install page 1, I could click the button, but no error message was displayed on the page or in any logs that I could find.

**Comment by mgrauer** [comment]
I realized I also needed to make logs dir writeable by www-data.  I was wondering why I had no logs.  This should also be documented in installation instructions.  Is it possible to pass a message to the server error logs in this case?  

Things were not working for me, I had no message to the user through the UI, no log files were created, and nothing in the apache error logs.  Hard to debug.  I'm done whining.  :baby:

**Comment by jamiesnape** [comment]
There are a couple of issues here:

1. Most errors are ignored at that stage as Midas does not think it is installed. This is not good, but since it is such a long standing behavior I probably will not be able to do anything about it anytime soon.
2. Logs are automatically directed to the syslog when the logs directory is not writable. You did not see an error because of the above behavior.

The documentation is just being finalized and will be ready very soon.
