### ISSUE TITLE
Uploader Freezing 

### ISSUE THREAD

**Issue by kipohl** [midasplatform/Midas#89]
Uploader freezes when user is not allowed to upload to a folder. Giving an error message would be very helpful

**Comment by jcfr** [comment]
:+1:

**Comment by jamiesnape** [comment]
Which uploader? There are several. Which version of Midas are you using?

**Comment by jcfr** [comment]
Most likely http://slicer.kitware.com/midas3

**Comment by jcfr** [comment]
Not sure which uploader ... I suspect it is independent of the uploader and is due to permission issues.

**Comment by jamiesnape** [comment]
A lot of the uploading logic has been rewritten, so I will have to put this on hold until I can determine if it is still an issue. It is not something I have observed.

**Comment by jamiesnape** [comment]
Is this still in a problem in 3.4.0?
