### ISSUE TITLE
API module must be enabled to be able to upload files

### ISSUE THREAD

**Issue by chrisbgp** [midasplatform/Midas#94]
error msg from midas:
The connection to the server was interrupted, press the Resume Upload button to resume.

apache error:
PHP Fatal error:  Class 'Api_AppController' not found in /var/www/midas/modules/api/controllers/JsonController.php on line 23, referer: http://xxxx/midas/admin

any ideas? thanks!

**Comment by jamiesnape** [comment]
Enable the API module.

**Comment by chrisbgp** [comment]
Thanks! works now. Can you please put this into the installation documentation or make the error message in the upload window more clear?
